marketing:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: db
      host: rc1b-0bjpn0fr8v02tfnp.mdb.yandexcloud.net
      port: 9440
      user: admin
      password: Qwerty123
      secure: True
      socket_timeout: [300000]